[package]
name = "galileo-tier-database"
version = "0.3.2"
authors = ["Dynisious <daniel.bechaz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-preview = "0.3.0-alpha"
